version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
 
# permissions:
#   #set permission to all files inside the "folder1" folder
#   - object: /home/ec2-user/app/
#     pattern: "*"
#     owner: ec2-user
#     mode: 755
#     type:
#       - file
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: root
  AfterInstall:
    - location: scripts/build_image.sh
      timeout: 400
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: root
