version: 0.0
os: linux
files:
  - source: docker/JarCICD-AWSCodeDeploy.tar.gz
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: ec2-user
