trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - pom.xml

pool:
  vmImage: 'ubuntu-latest'

# variables:
  # - group: Build-Variable-Group
  # - name: MAVEN_CACHE_FOLDER
  #   value: $(Pipeline.Workspace)/.m2/repository
  # - name: MAVEN_OPTS
  #   value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  # - task: DownloadSecureFile@1
  #   name: settingsxml
  #   inputs:
  #     secureFile: 'settings.xml'

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       New-Item -Type Directory -Force "${HOME}/.m2"
  #       Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
 
  # - task: Maven@3
  #   displayName: Run MUnit Tests (mvn test)
  #   inputs:
  #     publishJUnitResults: true
  #     goals: 'clean test'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      #mavenAuthenticateFeed: true
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      effectivePomSkip: true
      sonarQubeRunAnalysis: false
      goals: 'clean install package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/target/*.jar'
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: DemoApplication
      publishLocation: Container