version: "3"

services:

  fluentd:
    container_name: fluentd
    restart: always
    image: fluent/fluentd:v1.15.0-1.0
    volumes:
      - /Users/ajeetyadav/Projects/Freelancing Projects/Github-Sonor-ELK/Jar-CICD:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - fluentd_network

  app:
    restart: always
    container_name: jarcicd
    build: .
    ports:
      - "80:8080"
    networks:
        - fluentd_network
    depends_on:
      - fluentd
    environment:
      - DEBUG
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: jarcicd

networks:
  fluentd_network:
    driver: bridge
