name: Push and Trigger AWS Code Deploy

on:
  #push:
    #branches:
     # - master
  workflow_dispatch:

jobs:
  continuous-deployment:
    name: continuous-deployment
    runs-on: ubuntu-latest
    steps:
      # Step 2
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build application
        run: |
          mvn -B clean package -DskipTests --file pom.xml
#       - name: Upload Jar
#         uses: actions/upload-artifact@v2
#         with:
#           name: artifact
#           path: target/Jar-CICD-0.0.1-SNAPSHOT.jar

      # Step 2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name JarDeploy \
            --deployment-group-name Jar-deployment-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

     
