name: Docker Build and Push
on:
   workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
            java-version: '8'
      - name: Build application
        run: |
            mvn -B clean package -DskipTests --file pom.xml
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
            image: imajeetyadav/jar-cicd
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
