name: Docker Image CI

on:
#   push:
#     branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      -
        name: Checkout 
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      -
        name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34 # v2.7.0
      -
        name: Build and push
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }} 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jar-cicd:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/jar-cicd:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/jar-cicd:buildcache,mode=max
